name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install deps
      run: sudo apt-get install libdb++-dev build-essential libtool
    - name: update deps
      run: sudo apt-get update 
    - name: install some more deps
      run: sudo apt-get install autotools-dev automake pkg-config bsdmainutils python3 libssl-dev libevent-dev libboost-system-dev libboost-filesystem-dev libboost-chrono-dev libboost-test-dev libboost-thread-dev libqt5gui5 libqt5core5a libqt5dbus5 qttools5-dev qttools5-dev-tools libprotobuf-dev protobuf-compiler libzmq3-dev
    - name: update some more deps
      run: sudo apt-get update    
    - name: autogen
      run: ./autogen.sh
    - name: configure
      run: ./configure --disable-wallet 
    - name: make 
      run: make
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
